# Generated by Django 5.1.6 on 2025-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
