# Generated by Django 5.1.6 on 2025-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0002_notification_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_content', models.TextField()),
                ('response_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
