# Generated by Django 5.1.6 on 2025-02-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0003_recentemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentemail',
            old_name='sent_at',
            new_name='received_at',
        ),
        migrations.AddField(
            model_name='recentemail',
            name='sender',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='recentemail',
            name='subject',
            field=models.CharField(default='No Subject', max_length=255),
        ),
    ]
