# Generated by Django 5.1.6 on 2025-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0004_rename_sent_at_recentemail_received_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('tool', models.CharField(choices=[('scrapy', 'Scrapy'), ('playwright', 'Playwright')], max_length=20)),
            ],
        ),
    ]
