# Generated by Django 5.1.6 on 2025-04-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0006_schedulednotificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('notification_page_url', models.URLField()),
            ],
        ),
    ]
