# Generated by Django 5.1.6 on 2025-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0007_notificationpagemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperchoice',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperchoice',
            name='last_attempted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scraperchoice',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraperchoice',
            name='tool',
            field=models.CharField(choices=[('scrapy', 'Scrapy'), ('playwright', 'Playwright'), ('requests', 'Requests')], max_length=20),
        ),
    ]
